name: sam-nestkast
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.2
  - pip:
      - segment-anything
      - torchvision==0.16.*
      - torch==2.1.*           # Belangrijk voor GPU!
      - torchaudio==2.1.*
      - opencv-python==4.8.*
      - matplotlib==3.8.*
      - ipykernel==6.25.*
      - jupyterlab==4.0.*
